FROM ghcr.io/mend/renovate-ce:6.7.0@sha256:385f127981ec3601ea829e5671d758c7cfd7552e3defa31699f2d693b008e068

USER 0
ENV HOME=/home/ubuntu
ENV APP_ROOT=/usr/src/app

RUN rm -rfv /etc/apt/sources.list /etc/apt/sources.list.d/*.list