FROM ghcr.io/mend/renovate-ce:6.11.0@sha256:4cea86822cbc01bd3a7bd92d1f15d89585d77981a196b7c09ab67fb0b0665cd9

USER 0
ENV HOME=/home/ubuntu
ENV APP_ROOT=/usr/src/app

RUN rm -rfv /etc/apt/sources.list /etc/apt/sources.list.d/*.list